### PR TITLE
Chore/install

### PR DESCRIPTION
**Pull request by Ross-Esmond**
I managed to get the install working with pip alone, which should consolidate the installation process between windows and mac. I was going to keep a lot more of the old install instructions, but some of the links were dead, so it's been completely rewritten.

### CODE REVIEW

**Comment by Ross-Esmond** [comment]
Two separate branches now touch the README. If we pull one I'll fix the other. Or I could switch to one big pull request if we're not worried about granularity. I'm operating under standard open-source etiquette at the moment.

**Comment by cmcfadden** [comment]
Have you been able to actually run this and tested with cores? I didn't think the feature extraction worked properly with newer OpenCV, but maybe that's changed. I also thought you needed some sort of system libraries install for OpenCV, in addition to the python lib?

**Comment by Ross-Esmond** [comment]
It definitely runs. I successfully stitched two stacks of images together on my side machine after following my instructions precisely, but I only tested the most basic functionality. If you know of any other specific features I should test I can hit those as well. I can't say anything about feature extraction or cores.

What I can say is that the SIFT algorithm—the core feature that was missing with more recent versions of opencv—is available in opencv-contrib-python. It was hidden in opencv and opencv-python because it was patented in the US. You could only use it if you compiled opencv with a "non-free" flag, but one of the versions of opencv accidentally included it by default. That's the version you were on. Opencv-contrib-python, the package I switched to, has the "non-free" flag set to true, and so it builds with the SIFT algorithm by default. That's why I was able to switch to the most recent version.

By the way, the SIFT patent is twenty-one years old as of March of this year, so it has expired. The Opencv team has been informed and they're considering turning the feature on by default.

Its possible anaconda is doing something else that I'm not aware of. If you know of more issues with pip I can check for those as well.

I can also prepare a lighter rewrite of the README which cleans up dead links but keeps all the instructions that were there before.

**Comment by Waynewaynehello** [comment]
Not sure if this will reach the intended recipient, but I'm glad to see
that development is still going on with this project. I reached out a while
ago intending (but never getting around) to using this for my LadyBug
scanner project, which uses a 3D printer or other CNC to scan by taking a
regular grid of overlapping images using a USB microscope. Example data on
a PCB here:
https://drive.google.com/file/d/1z4HVS1OW51BIg2poLdHDMqvHnxTrtxkN/view
Would love to see an attempt on it; happy to provide more info and a
plethora of other example sets if needed.

~Ahron

**Comment by cmcfadden** [comment]
Thanks for the heads up on opencv. Maybe I'd just understood how the openCV setup worked in Anaconda. Let's go ahead and merge this!

**Pull request merged**
